version: '3.8'

services:
  # Postgres database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: stockmentions
      POSTGRES_USER: stockmentions
      POSTGRES_PASSWORD: stockmentions_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockmentions -d stockmentions"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stockmentions

  # Redis for caching (optional but recommended)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stockmentions

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stockmentions.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - stockmentions
    profiles:
      - admin

volumes:
  postgres_data:
  redis_data:

networks:
  stockmentions:
    driver: bridge